FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /src

# Копируем только проект для восстановления зависимостей
COPY *.csproj .
RUN dotnet restore

# Копируем остальные файлы
COPY . .

# Устанавливаем инструменты для EF
RUN dotnet tool install --global dotnet-ef

EXPOSE 8080
EXPOSE 8081

# Используем watch для hot reload
CMD ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080", "--non-interactive"]